### ISSUE TITLE
Unresolved reference: hasCppObject

### ISSUE THREAD

**Issue by chanjungkim** [rive-app/rive-android#270]
Unresolved reference: hasCppObject

why does it happen?

**Comment by umberto-sonnino** [comment]
HI @chanjungkim, can you give us a few more details about what you're trying to do?

More specifically:

- Please provide the most _minimal repro_ you can
If the problem is small enough, paste a code snippet
Otherwise, you can attach a ZIP archive or paste a link to a GitHub repository with the app bundle that is reproducing the issue

- Provide the source `.riv`/`.rev` file(s)

- Give us a clear and concise description of what you expected to happen.

- Which Device & Versions you're running this on
Device: [e.g. Android Emulator, Pixel 4a] 
SDK Level [e.g. Android SDK API Level 30]

- Add any other context about the problem here
